name: Build Android APK

on:
  push:
    branches: [ main, cursor/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Java 19
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'
        cache: 'gradle'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '34'
        build-tools: '30.0.3'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk